language: node_js
node_js:
- 11.4.0
- 10.16.0
script: npm run test:coverage && cat ./coverage/lcov.info | npm run coveralls
env:
  global:
    - DOCKER_USERNAME=rowma
    secure: L/DN6HUNqDDT+cxXSupRYY+X/S7B+9tjhbMfAjUyi2VS+aWjjEr1uB4BwBSZ5UOvyFptIhzpRJtW6Fkye/8Oo9lv+UNwG/XO9jytW2SAH6L+XY46LsqhGG3Q3jqMeKC3wdP/fTw3VQ7E4bxUHiz8N1AFhxPdNukNOgPVlwix5C5trGLgwNQLJJ6qcy+gzwvxvVuNlhdoTj3N60Dx5+akvJiChArTpeQV6nZY/j3phw+wv5i3VJag77j9RxlpFqjjPAtX7sWh0c1hcU4MdaaGpUrRfBizWPN6uU9Y42/gjy2H1kdNnIMkf4de4I32ip18On5BiNZyN9Veafk5HJAEBXUlzrPQ4jVZL/d/s9NE5XHq9DH197joFVDO1ZC4DbSS5P7Uc2liEicirELiOcMX1cHhpBiV0v2f7b9Yex7VQx4QQoojyPO+VSNdOKypeGxNNTOkZzVVUHEx2HRPE8bM3F+lsIpaeGnqgmRENff3AqCRD2XSE7K+3niZWDT4dKEOjioNh1INl5yFiLDwnOXxtbeJILYnGLCwc8g8i12h+PppzRt015xkivxxKlTkUP7fWnjZcytydS1cvm9jbSCvHnv9CQfBB7ASaI8U3L8HKQaZniDHC4k6zszPHIGyc2kiO5pLgGVONU3U4X2kmpWpohHhaKhjNMxmfEXcC5fLIMU=
