#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push rowma/rowma

sudo add-apt-repository ppa:eugenesan/ppa
sudo apt-get install jq -y

curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | \
  sudo tee -a /usr/bin/ecs-deploy
sudo chmod +x /usr/bin/ecs-deploy

ecs-deploy -c rowma-connection-manager-cluster -n rowma-connection-manager-service -i rowma/rowma:latest
